# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: r_finances_development

test:
  <<: *default
  database: r_finances_test

production:
  <<: *default
  # Render uses DATABASE_URL for everything.
  url: <%= ENV["DATABASE_URL"] %>
